name: "Static Analysis"

on:
  pull_request:
    branches:
      - "master"
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - lib/**
      - phpstan*
      - psalm*
      - tests
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - lib/**
      - phpstan*
      - psalm*
      - tests

jobs:
  static-analysis:
    name: "Static Analysis"
    uses: "doctrine/.github/.github/workflows/static-analysis.yml@3.0.0"
